keys:
  - &host_beef age1wq5xj5mwv9xk4tp26cxc4xqjq9xd9hwqv0zeemawl2cc8sarmqesw366dh
  - &host_butcher age1nleq0q2kzh2zn4pyr0dcy0zjnsr6sx8c5ttjahhfttkltsr2s3ksahhpkx
  - &host_entropy age10r9fcpj4z6nc9p5n3e6eqdy9kkmvp0kafpj02qwyvwnhs3ev2pts8qawyt
  - &host_nakulaptop age1m6gzjlvx5paan69evccl6kywj0ghdk46prumx4jn4hxcrxd4re6qckdl9w
  - &host_nomad age1y2f4jzfqjscgvwe3w3q8jmadtvxlsudk3c49lhqtdvatu7fwtdusez9fm9
  - &host_seed age16wsn8f4wrk4f8ssk76h8hd57e4mquychcju0ny5qhvkzvq0teplqrct0yd
  - &host_tentacle age190tmygg8xmn9tkj4yjgemvdd8s4tnmycr9n4qfrr0l97zxfq3gjs36xsn8
  - &user_dave age1upzm9um3qljxlmxcg8vl35d7eyeqtnsfcnqlh3wtnj46dhfzwyrqa80avw
  - &user_ireen age1477n5xa2cr4tgdy80vxg24tsdcrcmzarn4ad99tjvrsjedq6sqpqsxyrms
  - &host_b2 age1gx4830zkjyfk5plednerdwzu2v4yfmts3up495wtk7dxv2frsqsqpu9hy6
creation_rules:
  - path_regex: hosts/common/secrets/.*
    key_groups:
      - age:
          - *host_beef
          - *host_butcher
          - *host_entropy
          - *host_nakulaptop
          - *host_nomad
          - *host_seed
          - *host_tentacle
          - *user_dave
          - *user_ireen
          - *host_b2
  - path_regex: users/secrets.yaml
    key_groups:
      - age:
          - *host_beef
          - *host_butcher
          - *host_entropy
          - *host_nakulaptop
          - *host_tentacle
          - *host_seed
          - *host_nomad
          - *user_dave
          - *host_b2
  - path_regex: hosts/beef/secrets/.*
    key_groups:
      - age:
          - *host_beef
          - *user_dave
  - path_regex: hosts/butcher/secrets/.*
    key_groups:
      - age:
          - *host_butcher
          - *user_dave
  - path_regex: hosts/entropy/secrets/.*
    key_groups:
      - age:
          - *host_entropy
          - *host_nomad
          - *user_dave
  - path_regex: hosts/nakulaptop/secrets/.*
    key_groups:
      - age:
          - *host_nakulaptop
          - *user_dave
          - *user_ireen
  - path_regex: hosts/nomad/secrets/.*
    key_groups:
      - age:
          - *host_nomad
          - *host_beef
          - *user_dave
  - path_regex: hosts/seed/secrets/.*
    key_groups:
      - age:
          - *host_seed
          - *host_beef
          - *user_dave
  - path_regex: hosts/tentacle/secrets/.*
    key_groups:
      - age:
          - *host_tentacle
          - *host_beef
          - *user_dave
  - path_regex: hosts/b2/secrets/.*
    key_groups:
      - age:
          - *host_b2
          - *host_nomad
          - *user_dave
          - *host_nomad
          - *user_dave
